[package]
name = "rust"
version = "0.1.0"
authors = ["CjS77", "Dunnock", "Krakaw"]

[dependencies]
actix-rt = "1.0"
actix = "0.9"
actix-web = "2.0"
actix-cors = "0.2"
actix-web-actors = "2.0"
actix-service = "1.0"
actix-files = "0.2"
actix-http = "1.0.1"
argon2rs = "0.2"
chrono = {version = "0.4", features = ["serde"]}
clap="2.32"
diesel = {version="1.4.4", default_features=false, features = ["postgres", "uuid", "chrono", "serde_json", "r2d2", "64-column-tables"]}
diesel_migrations="1.3"
dotenv = "0.13"
fake = { version = "1.2" }
fern = "0.5"
hex = "0.3.2"
itertools = "0.7"
jsonrpc-core = "8.0.1"
jwt = "0.4"
lettre = "0.8"
lettre_email = "0.9.2"
log = "0.4"
rand = "0.7"
reqwest = { version = "0.10", features = ["blocking", "json"] }
r2d2 = "0.8"
rust-crypto = "0.2"
rustc-serialize = "0.3"
scheduled-thread-pool = "0.2"
secp256k1 = { version = "0.11.2", features = ["rand", "serde"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_with = "0.2"
time="0.1"
url = "2.1.1"
uuid = { version = "0.6", features = ["serde", "v4"] }
validator = "0.8"
validator_derive = "0.8"
