[package]
name = "Rust"
version = "0.1.0"
authors = ["CjS77 <cayle.sharrock@gmail.com>"]

[dependencies]
actix = "0.7"
actix-web = "=0.7.13"
argon2rs = "0.2"
chrono = {version = "0.4", features = ["serde"]}
clap="2.32"
diesel = { version = "1.3", features = ["postgres", "uuid", "chrono","numeric", "serde_json"] }
diesel_migrations="1.3"
dotenv = "0.13"
fake = { version = "1.2" }
fern = "0.5"
hex = "0.3.2"
itertools = "0.7"
jsonrpc-core = "8.0.1"
jwt = "0.4"
lettre = "0.8"
lettre_email = "0.8"
log = "0.4"
rand = "0.5"
reqwest = "0.9.22"
r2d2 = "0.8"
rust-crypto = "0.2"
rustc-serialize = "0.3"
scheduled-thread-pool = "0.2"
secp256k1 = { version = "0.11.2", features = ["rand", "serde"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_with = "0.2"
time="0.1"
url = "1.7.1"
uuid = { version = "0.6", features = ["serde", "v4"] }
validator = "0.8"
validator_derive = "0.8"
